# Generated by Django 4.0.4 on 2023-02-05 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('award', '0005_alter_awardscontestant_instagram_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AwardVotingWebhookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_votes', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('verified', models.BooleanField(default=False)),
                ('order_paid', models.BooleanField(default=False)),
                ('payment_state', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], default='pending', max_length=15)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('contestant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='award.awardscontestant')),
            ],
            options={
                'ordering': ('-amount',),
            },
        ),
    ]
