# Generated by Django 4.0.4 on 2023-02-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardvotingwebhookmodel',
            name='type_of_vote',
            field=models.CharField(choices=[('pageant-registration', 'pageant-registration'), ('pageant-vote', 'pageant-vote'), ('awards-vote', 'awards-vote')], default='undefined', max_length=30),
        ),
        migrations.AddField(
            model_name='webhooktestmodel',
            name='payment_type',
            field=models.CharField(choices=[('pageant-registration', 'pageant-registration'), ('pageant-vote', 'pageant-vote'), ('awards-vote', 'awards-vote'), ('undefined', 'undefined')], default='undefined', max_length=30),
        ),
    ]
