# Generated by Django 4.0.4 on 2023-02-06 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_awardvotingwebhookmodel_type_of_vote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVotingWebhookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_votes', models.IntegerField(default=0)),
                ('contestant_id', models.CharField(max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('verified', models.BooleanField(default=False)),
                ('order_paid', models.BooleanField(default=False)),
                ('type_of_vote', models.CharField(choices=[('pageant-registration', 'pageant-registration'), ('pageant-vote', 'pageant-vote'), ('awards-vote', 'awards-vote'), ('undefined', 'undefined')], default='undefined', max_length=30)),
                ('payment_state', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], default='pending', max_length=15)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-amount',),
            },
        ),
        migrations.DeleteModel(
            name='AwardVotingWebhookModel',
        ),
    ]
