# Generated by Django 4.0.4 on 2023-02-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_newvotingwebhookmodel_delete_awardvotingwebhookmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvotingwebhookmodel',
            name='contestant_id',
            field=models.IntegerField(),
        ),
    ]
