# Generated by Django 4.0.4 on 2023-02-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_alter_awardscontestant_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardscontestant',
            name='image2',
        ),
        migrations.AlterField(
            model_name='awardscontestant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='awardscontestant',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
