# Generated by Django 4.0.4 on 2023-02-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_remove_awardscontestant_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardscontestant',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='awardscontestant',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
