# Generated by Django 4.0.4 on 2023-04-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0006_newawardsregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardvotepurchase',
            name='contestant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='award.newawardsregistration'),
        ),
        migrations.DeleteModel(
            name='AwardsContestant',
        ),
    ]
