# Generated by Django 4.0.4 on 2023-04-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0007_alter_awardvotepurchase_contestant_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwardVotePurchase',
        ),
    ]
