# Generated by Django 4.0.4 on 2023-04-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0008_delete_awardvotepurchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newawardsregistration',
            options={'ordering': ('-number_of_votes',), 'verbose_name': 'Awards Registration', 'verbose_name_plural': 'Awards Registrations'},
        ),
        migrations.AlterField(
            model_name='newawardsregistration',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.awardscategory'),
        ),
    ]
