# Generated by Django 4.0.4 on 2023-05-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0009_alter_newawardsregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newawardsregistration',
            name='phone_no',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
