# Generated by Django 4.0.4 on 2022-05-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0014_registercontestant_is_evicted'),
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votepurchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votepurchase',
            name='contestant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contestants.registercontestant'),
            preserve_default=False,
        ),
    ]
