# Generated by Django 4.0.4 on 2022-05-19 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_alter_votepurchase_contestant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.AlterModelOptions(
            name='votepurchase',
            options={'ordering': ('-amount',)},
        ),
    ]
