# Generated by Django 4.0.4 on 2022-05-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
