# Generated by Django 4.0.4 on 2022-05-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0004_alter_registrationpurchase_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpurchase',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
