# Generated by Django 4.0.4 on 2022-05-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0005_registrationpurchase_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterContestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('instagram_handle', models.CharField(max_length=30)),
                ('tell_us', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('image1', models.ImageField(default='defaultuser.jpg', upload_to='contestant/%Y/%m/%d')),
                ('image2', models.ImageField(default='defaultuser.jpg', upload_to='contestant/%Y/%m/%d')),
                ('gender', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
