# Generated by Django 4.0.4 on 2022-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0006_registercontestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercontestant',
            name='refnum',
            field=models.CharField(default='INDINVO', max_length=200),
            preserve_default=False,
        ),
    ]
