# Generated by Django 4.0.4 on 2022-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0007_registercontestant_refnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercontestant',
            name='tell_us',
            field=models.TextField(default='I WANT TO WIN'),
        ),
    ]
