# Generated by Django 4.0.4 on 2022-05-15 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0008_alter_registercontestant_tell_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercontestant',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registrationpurchase',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
