# Generated by Django 4.0.4 on 2022-05-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0012_alter_registercontestant_number_of_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercontestant',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
