# Generated by Django 4.0.4 on 2022-05-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0013_alter_registercontestant_number_of_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercontestant',
            name='is_evicted',
            field=models.BooleanField(default=False),
        ),
    ]
