# Generated by Django 4.0.4 on 2022-06-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0015_alter_registercontestant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercontestant',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
