# Generated by Django 4.0.4 on 2023-02-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0017_alter_registercontestant_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registercontestant',
            name='image2',
        ),
        migrations.AlterField(
            model_name='registercontestant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registercontestant',
            name='instagram_handle',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='registercontestant',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='registercontestant',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
