# Generated by Django 4.0.4 on 2023-04-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0019_alter_registercontestant_instagram_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPageantRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('instagram_handle', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('height_type', models.CharField(choices=[('Ft', 'Ft'), ('Mm', 'Mm')], max_length=4)),
                ('height', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('state_of_residence', models.CharField(max_length=300)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=300)),
                ('agency_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('modeling_experience', models.CharField(blank=True, choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('professional', 'professional')], max_length=30)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('number_of_votes', models.IntegerField(default=0)),
                ('is_evicted', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-number_of_votes',),
            },
        ),
    ]
