# Generated by Django 4.0.4 on 2023-04-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0020_newpageantregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpageantregistration',
            name='is_in_agency',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
