# Generated by Django 4.0.4 on 2023-04-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_alter_votepurchase_contestant_id'),
        ('contestants', '0021_newpageantregistration_is_in_agency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterContestant',
        ),
        migrations.DeleteModel(
            name='RegistrationPurchase',
        ),
    ]
