# Generated by Django 4.0.4 on 2023-05-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0023_alter_newpageantregistration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newpageantregistration',
            options={'ordering': ('-number_of_votes',), 'verbose_name': 'Pageantry Registration', 'verbose_name_plural': 'Pageantry Registrations'},
        ),
    ]
