# Generated by Django 4.0.4 on 2022-06-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=100)),
                ('image', models.ImageField(default='defaultuser.jpg', upload_to='blogs/%Y/%m/%d')),
                ('author', models.CharField(default='No Author', max_length=50)),
                ('description', models.TextField(default='No Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
