# Generated by Django 4.0.4 on 2022-06-10 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_is_displayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 13, 42, 54, 120189, tzinfo=utc)),
        ),
    ]
